version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: godrive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/godrive
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - media_files:/app/media
      - static_files:/app/static
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  bot:
    build: ./bot
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/godrive
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./bot:/app
    depends_on:
      - db
      - redis
      - backend

volumes:
  postgres_data:
  media_files:
  static_files:

